config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Signup
  root 'sessions#new'
  scope '/signup' do
    get '/'  => 'users#new', as: :signup
    post '/'  => 'users#create'
  end
  # Login
  scope '/login' do
    get '/'  => 'sessions#new', as: :login
    get '/error'  => 'sessions#error'
    get '/error/passwd'  => 'sessions#newpass'
    get '/session'  => 'sessions#loggedout'
    post '/'  => 'sessions#create'
  end
  # Logout
  scope '/logout' do
    get '/' => 'sessions#destroy', as: :logout
  end
  # Dashboard
  scope '/dash' do
    get '/' => 'dashboard#new', as: :dash
  end
  scope '/zone' do
    get '/:id' => 'zone#index', as: :zone
  end
  # Admin
  scope '/admin' do
    get '/' => 'admin#new', as: :admin
    # Users
    scope '/users' do
      get '/' => 'admin#users', as: :admin_users
      get '/lock/:id' => 'admin#lock_account', as: :admin_lock_user
      get '/unlock/:id' => 'admin#unlock_account', as: :admin_unlock_user
      scope '/make' do
        get '/admin/:id' => 'admin#make_admin', as: :admin_create_admin
        get '/user/:id' => 'admin#make_user', as: :admin_create_user
      end
      post '/edit' => 'admin#edit_user', as: :admin_edit_users
    end
    # Servers
    scope '/servers' do
        get '/' => 'admin#servers', as: :admin_servers
        get '/destroy/:id' => 'admin#destroy', as: :admin_destroy_servers
    end
    scope '/templates' do
      get '/' => 'admin#templates', as: :admin_templates
      post '/edit' => 'admin#edit_template', as: :admin_edit_templates
      get '/destroy/:id' => 'admin#destroy_template', as: :admin_destroy_templates
      post '/create' => 'admin#create_template', as: :admin_create_templates
    end
    scope '/groups' do
      get '/' => 'admin#groups', as: :admin_groups
      post '/edit' => 'admin#edit_group', as: :admin_edit_groups
      get '/destroy/:id' => 'admin#destroy_group', as: :admin_destroy_groups
      post '/create' => 'admin#create_group', as: :admin_create_groups
    end
    scope '/support' do
      get '/' => 'admin#support', as: :admin_support
      get '/closed' => 'admin#closed_tickets', as: :admin_support_closed
      get '/close/:id' => 'admin#close_ticket', as: :admin_support_close
      get '/open/:id' => 'admin#open_ticket', as: :admin_support_open
      get '/view/:id' => 'admin#view_ticket', as: :admin_support_view
      post '/reply/:id' => 'admin#reply_ticket', as: :admin_support_reply
    end
    scope '/announcements' do
      get '/' => 'admin#announcements', as: :admin_announcements
      post '/create' => 'admin#create_announcement', as: :admin_announcements_create
      get '/destroy/:id' => 'admin#destroy_announcement', as: :admin_announcements_destroy
      post '/edit' => 'admin#edit_announcement', as: :admin_announcements_edit
    end
    scope '/zones' do
      get '/' => 'admin#zones', as: :admin_zones
      get '/destroy/:id' => 'admin#destroy_node', as: :admin_zones_destroy
      post '/add' => 'admin#add_zone', as: :admin_create_zones
      get '/delete/:id' => 'admin#destroy_zone', as: :admin_destroy_zones
    end
    scope '/pools' do
      get '/' => 'admin#pools', as: :admin_pools
      post '/create' => 'admin#create_pool', as: :admin_pools_create
      get '/destroy/:id' => 'admin#destroy_pool', as: :admin_pools_destroy
    end
    scope '/plans' do
      get '/' => 'admin#plans', as: :admin_plans
      post '/create' => 'admin#create_plan', as: :admin_plans_create
      get '/destroy/:id' => 'admin#destroy_plan', as: :admin_plans_destroy
    end
  end
  # Account
  scope '/account' do
    get '/' => 'account#new', as: :account
    post '/' => 'account#update'
    get '/saved' => 'account#updated', as: :account_saved
    get '/error' => 'account#error', as: :account_error
  end
  # Activity
  scope '/activity' do
    get '/' => 'activity#new', as: :activity
  end
  # Reset
  scope '/reset' do
    get '/' => 'reset#new', as: :reset
    post '/' => 'reset#check'
    get '/error' => 'reset#chgerror', as: :reset_error_reset
    get '/done' => 'reset#done', as: :reset_done
    get '/:id' => 'reset#reset'
    post '/:id' => 'reset#change', as: :reset_reset
  end
  # Verify
  scope '/verify' do
    get '/' => 'verify#new', as: :verify
    post '/' => 'verify#verify'
    get '/error' => 'verify#error', as: :verify_error
  end
  scope '/api' do
    scope '/v1' do
      get '/auth' => 'api#authenticate'
      post '/register' => 'api#registeruser'
      post '/verify' => 'api#verify'
      get '/reset' => 'api#reset'
      get '/details' => 'api#userdetails'
      patch '/password' => 'api#userpasswd'
      get '/tickets' => 'api#supporttickets'
      get '/bills' => 'api#showbills'
      get '/logs' => 'api#showlogs'
      patch '/style' => 'api#updatestyle'
      scope '/bill' do
        get '/:id' => 'api#viewbill'
      end
      scope '/ticket' do
        get '/:id' => 'api#viewticket'
        post '/create' => 'api#createticket'
      end
      get '/run_accounting' => 'api#run_accounting'
      get '/run_generation' => 'api#run_generation'
    end
  end
  scope '/create' do
    get '/' => 'zone#create', as: :new_zone
    post '/' => 'zone#make'
  end
  scope '/errors' do
    get '/400' => 'errors#e400'
    get '/401' => 'errors#e401'
    get '/403' => 'errors#e403'
    get '/404' => 'errors#e404'
    get '/405' => 'errors#e405'
    get '/406' => 'errors#e406'
    get '/422' => 'errors#e422'
    get '/500' => 'errors#e500'
    get '/501' => 'errors#e501'
  end
end

app/models/action.rb
class Action < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/geo_ip.rb
class GeoIp < ApplicationRecord
end

app/models/geo_ip2_isp.rb
class GeoIp2Isp < ApplicationRecord
end

app/models/ip_pool.rb
class IpPool < ApplicationRecord
end

app/models/os_collection.rb
class OsCollection < ApplicationRecord
end

app/models/os_template.rb
class OsTemplate < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/restriction.rb
class Restriction < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/vm.rb
class Vm < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_secure_token :route_token, length: 32
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zone_helper.rb
module ZoneHelper
end

app/views/admin/announcements.html.erb
<% content_for :title, "Announcements" %>
<% content_for :new_layout, "1" %>
<% content_for :bss, "bootstrapSwitch.css" %>

<%= render "shared/alerts" %>

<%= render "shared/navbar" %>

<div class="container pt-4">

  <h1 class="text-white">Administration Dashboard</h1>

  <%= render "shared/admin_navbar_announcements" %>

  <div class="tab-content">

    <div id="buttons" class="mb-3">
      <div class="clearfix">
        <div class="float-right">
          <a href="#"><input type="submit" value="Create Announcement" class="btn btn-small btn-success create"
              data-disable-with="Create Announcement" data-toggle="modal" data-target="#create-modal"></a>
        </div>
      </div>
    </div>


    <table class="table text-white">
      <thead>
        <tr>
          <th style="text-align: center;">Announcement</th>
          <th style="text-align: center;">Options</th>
        </tr>
      </thead>

      <tbody>
        <% Announcement.all.each do |a| %>
        <tr class="table-item">
          <th style="text-align: center;"><%= a.announcements %></th>
          <th style="text-align: center;"><a href="<%= admin_announcements_destroy_path(a.id) %>">Destroy</a> / <a
              href="#" class="edit" data-announcement="<%=a.announcements%>" data-aid="<%=a.id%>">Edit</a></th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= form_for(:create, :url => admin_announcements_create_path) do |f| %>
<div id="create-modal" class="modal hide fade">
  <div class="container modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">
    <div class="modal-header no-border">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>Create Announcement</h3>
    </div>
    <div class="modal-body">
      <div class="form-group">

        <label>Announcement</label>
        <%= f.text_area :announcement, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Announcement", :rows => "3" %>

      </div>
    </div>
    <div class="modal-footer no-border">

      <%= f.submit "Create", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>
</div>
<%end%>

<%= form_for(:edit, :url => admin_announcements_edit_path) do |f| %>
<div id="edit-modal" class="modal fade" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">
    <div class="modal-header no-border">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>Edit Announcement</h3>
    </div>
    <div class="modal-body">
      <div class="form-group">

        <label>Announcement</label>
        <%= f.text_area :announcement, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Announcement", :rows => "3" %>

      </div>
    </div>
    <div class="modal-footer no-border">

      <%= f.submit "Edit", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>
</div>
<%end%>


<script>
  $(document).ready(function () {
    $('.edit').click(function () {
      announcement = $(this).data('announcement');
      aid = $(this).data('aid');
      modal = $('#edit-modal');
      $('#edit_announcement').html(announcement);
      $('#edit_aid', modal).val(aid);
      modal.modal('show');
    });
    $('.create').click(function () {
      $('#create-modal').modal();
      $(document).off('focusin.modal');
    });
  });

  
</script>

<%= render "shared/footer" %>

app/views/admin/groups.html.erb
<% content_for :title, "OS Collections" %>
<% content_for :new_layout, "1" %>

<%= render "shared/alerts" %>

<%= render "shared/navbar" %>

<div class="container pt-4">
  <h1 class="text-white">Administration Dashboard</h1>

  <div class="row">
    <div class="span3">
    <%= render "shared/admin_navbar_groups" %>
  
      <div class="span9">
        <div class="tab-content">

          <div id="buttons" class="mb-3">
            <div class="clearfix">
              <div class="float-right">
                <a href="#"><input type="submit" value="Create Collection" class="btn btn-small btn-success create" data-disable-with="Create Collection"></a>
              </div>
            </div>
          </div>

          <table class="table table-bordered table-striped" id="vservers">
            <thead>
              <tr>
                <th style="text-align: center;">Name</th>
                <th style="text-align: center;">Fragment</th>
                <th style="text-align: center;">Description</th>
                <th style="text-align: center;">Options</th>
              </tr>
            </thead>
            <tbody>
              <% OsCollection.all.each do |c| %>
                <tr class="table-item">
                  <th style="text-align: center;"><%= c.name %></th>
                  <th style="text-align: center;"><%= c.url %></th>
                  <th style="text-align: center;"><%= c.description %></th>
                  <th style="text-align: center;"><a href="#" class="edit" data-name="<%=c.name%>" data-fragment="<%=c.url%>" data-description="<%=c.description%>" data-gid="<%= c.id %>">Edit</a> / <a href="<%= admin_destroy_groups_path(c.id) %>">Delete</a></th>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= form_for(:edit, :url => admin_edit_groups_path) do |f| %>
<div id="edit-modal" class="modal hide fade">
  <div class="container modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">
    <div class="modal-header no-border">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>Edit Collection</h3>
    </div>
    <div class="modal-body no-border">
      <div class="form-group">

        <label>Name</label>
        <%= f.text_field :name, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Name", :rows => "1" %>

        <label>URL fragment</label>
        <%= f.text_field :fragment, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "URL", :rows => "1" %>

        <label>Description</label>
        <%= f.text_area :description, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Description", :rows => "2" %>
        <%= f.hidden_field :gid %>

      </div>
    </div>
    <div class="modal-footer no-border">

      <%= f.submit "Edit", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>
</div>
<%end%>

<%= form_for(:create, :url => admin_create_groups_path) do |f| %>
<div id="create-modal" class="modal hide fade">
  <div class="container modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">
    <div class="modal-header no-border">
      <a class="close" data-dismiss="modal">&times;</a>
      <h3>Create Collection</h3>
    </div>
    <div class="modal-body">
    
      <div class="form-group">

      <label>Name</label>
      <%= f.text_field :name, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Name", :rows => "1" %>

      <label>URL fragment</label>
      <%= f.text_field :fragment, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "URL", :rows => "1" %>

      <label>Description</label>
      <%= f.text_area :description, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Description", :rows => "2" %>

      </div>

    </div>
    <div class="modal-footer no-border">

      <%= f.submit "Create", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>
</div>
<%end%>

<script>
  $(document).ready(function() {
    $('.edit').click(function() {
    name = $(this).data('name');
    fragment = $(this).data('fragment');
    description = $(this).data('description');
    gid = $(this).data('gid');
    modal = $('#edit-modal');
    $('#edit_name').attr("value", name);
    $('#edit_fragment').attr("value", fragment);
    $('#edit_description').html(description);
    $('#edit_gid').attr("value", gid);
    modal.modal('show');

    });
    $('.create').click(function() {
      modal = $('#create-modal');
      $('#create_name', modal).val('');
      $('#create_fragment', modal).val('');
      $('#create_description', modal).val('');
      modal.modal('show');

    });
  });
</script>

<%= render "shared/footer" %>

app/views/admin/new.html.erb
<% content_for :title, "Administration" %>
<% content_for :new_layout, "1" %>

<%= render "shared/alerts" %>

<%= render "shared/navbar" %>

<div class="container pt-4">

  <h1 class="text-white">Administration Dashboard</h1>

  <div class="row">
      <%= render "shared/admin_navbar_home" %>
  </div>
  
  <div class="tab-content">
    <div class="tab-pane active" style="position: relative; top: 100px;">
      <p style="font-size: 40px; text-align: center;">Please pick something </p>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/admin/templates.html.erb
<% content_for :title, "OS Templates" %>
<% content_for :new_layout, "1" %>

<%= render "shared/alerts" %>

<%= render "shared/navbar" %>

<div class="container pt-4">

<h1 class="text-white">Administration Dashboard</h1>

<div class="row">
  <div class="span3">

<%= render "shared/admin_navbar_templates" %>
  <div class="span9">

    <div id="buttons" class="mb-3">
      <div class="clearfix">
        <div class="float-right">
          <a href="#"><input type="submit" value="Create Template" class="btn btn-small btn-success create" data-disable-with="Create Template"></a>
        </div>
      </div>
    </div>

        <table class="table table-bordered table-striped" id="vservers">
          <caption>OS Templates</caption>
          <thead>
            <tr>
              <th style="text-align: center;">Name</th>
              <th style="text-align: center;">Belongs to</th>
              <th style="text-align: center;">Image</th>
              <th style="text-align: center;">Options</th>
            </tr>
          </thead>
          <tbody>
              <% OsTemplate.all.each do |t| %>
                <tr class="table-item">
                  <th style="text-align: center;"><%= t.name %></th>
                  <th style="text-align: center;"><%= t.belongs_to %></th>
                  <th style="text-align: center;"><img src="/images/<%= t.os_image %>.png" width="100" height="100" /></th>
                  <th style="text-align: center;"><a href="#" class="edit" data-name="<%=t.name%>" data-belongs="<%=t.belongs_to%>" data-image="<%=t.os_image%>" data-tid="<%= t.id %>" data-iso="<%= t.image_location %>">Edit</a> / <a href="<%= admin_destroy_templates_path(t.id) %>">Delete</a></th>
              </tr><% end %>
                </tbody>
        </table>
                </div>
              </div>
            </div>


      </div>
      <%= form_for(:edit, :url => admin_edit_templates_path) do |f| %>
      <div id="edit-modal" class="modal hide fade">
        <div class="container modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">

          <div class="modal-header no-border">
            <a class="close" data-dismiss="modal">&times;</a>
            <h3>Edit Template</h3>
          </div>
          <div class="modal-body">
            <div class="form-group">

              <label>Name</label>
              <%= f.text_field :name, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Name", :rows => "1"  %>

              <label>Belongs to</label>
              <%= f.collection_select(:belongs, OsCollection.all, :id, :name, {:include_blank => 'Please Select One'}, :style => "width: 400px;") %>
              
              <label>Template Icon</label>
              <%= f.text_field :image, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Icon", :rows => "1"  %>
              <%= f.hidden_field :tid %>
              
              <label>ISO</label>
              <%= f.text_field :iso, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "ISO", :rows => "1"  %>

            </div>

          </div>
          <div class="modal-footer no-border">

            <%= f.submit "Edit", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
            <a href="#" class="btn" data-dismiss="modal">Cancel</a>
          </div>
        </div>
      </div>
      <%end%>

      <%= form_for(:create, :url => admin_create_templates_path) do |f| %>
      <div id="create-modal" class="modal hide fade">
        <div class="container modal-dialog modal-content card custom-item-bg-dark custom-modal text-white">
          <div class="modal-header no-border">
            <a class="close" data-dismiss="modal">&times;</a>
            <h3>Create Template</h3>
          </div>
          <div class="modal-body">
            <div class="form-group">

              <label>Name</label>
              <%= f.text_field :name, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Name", :rows => "1" %>

              <label>Belongs to</label>
              <%= f.collection_select(:belongs, OsCollection.all, :id, :name, {:include_blank => 'Please Select One'}, :style => "width: 400px;") %>

              <label>Template Icon</label>
              <%= f.text_field :image, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "Icon", :rows => "1"  %>
              
              <label>ISO</label>
              <%= f.text_field :iso, :style => "width: 400px;", :class => "form-control custom-input-dark", :placeholder => "ISO", :rows => "1"  %>

            </div>

          </div>
          <div class="modal-footer no-border">

            <%= f.submit "Create", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
            <a href="#" class="btn" data-dismiss="modal">Cancel</a>
          </div>
        </div>
      </div>
      <%end%>

  </div>
</div>
<script>
$(document).ready(function() {
  $('.edit').click(function() {
  name = $(this).data('name');
  belongs = $(this).data('belongs');
  image = $(this).data('image');
  tid = $(this).data('tid');
  iso = $(this).data('iso');
  modal = $('#edit-modal');
  $('#edit_name').attr("value", name);
  $('#edit_image').attr("value", belongs);
  $('#edit_description').html(image);
  $('#edit_tid').attr("value", tid);
  $('#edit_iso').attr("value", iso);
  modal.modal('show');

  });
  $('.create').click(function() {
    modal = $('#create-modal');
    $('#create_name', modal).val('');
    $('#create_belongs', modal).val('');
    $('#create_image', modal).val('');
    modal.modal('show');

  });
});
</script>
<%= render "shared/footer" %>

app/views/admin/users.html.erb
<% content_for :title, "Users" %>
<% content_for :new_layout, "1" %>

<%= render "shared/alerts" %>

<%= render "shared/navbar" %>

<div class="container pt-4">

<h1 class="text-white">Administration Dashboard</h1>

<%= render "shared/admin_navbar_users" %>
  <div class="span9">


      <div class="tab-content">

        <table class="table table-bordered table-striped" id="vservers">
          
          <thead>
            <tr>
              <th style="text-align: center;">Name</th>
              <th style="text-align: center;">Email</th>
              <th style="text-align: center;">Options</th>
            </tr>
          </thead>
          <tbody>
              <% User.all.each do |user| %>
                <tr class="table-item">
                  <th style="text-align: center;"><a target="_blank" href="https://lmgtfy.com/?q=<%=user.first_name%>+<%=user.last_name%>"><%= user.first_name %> <%= user.last_name %></a></th>
                  <th style="text-align: center;"><%= user.email %></th>
                  <th style="text-align: center;"><a href="<%if user.enabled == "1" %><%= admin_lock_user_path(user.id) %>">Lock<%else%><%= admin_unlock_user_path(user.id) %>">Unlock<%end%></a> / <% if user.level == "0" %><a href="<%= admin_create_admin_path(user.id) %>">Make Admin</a><% else %><a href="<%= admin_create_user_path(user.id) %>">Make User</a><% end %> / <a href="#" class="edit" data-fname="<%= user.first_name %>" data-lname="<%= user.last_name %>" data-uid="<%= user.id %>" data-email="<%= user.email %>">Edit</a></th>
              </tr><% end %>
                </tbody>
        </table>
                </div>
              </div>
            </div>


      </div>
      <%= form_for(:user, :url => admin_edit_users_path) do |f| %>
      <div id="modal" class="modal hide fade">
  			<div class="modal-header">
  				<a class="close" data-dismiss="modal">&times;</a>
  				<h3>Edit User</h3>
  			</div>
  			<div class="modal-body">
  				<p>

  				<div class="password">

  					<label>First Name</label>
            <%= f.text_field :fname, :style => "width: 400px;" %>

  					<br />
            <label>Last Name</label>
            <%= f.text_field :lname, :style => "width: 400px;" %>
            <%= f.hidden_field :userid %>
  					<br />
            <label>Email</label>
            <%= f.text_field :email, :style => "width: 400px;" %>
  					<br />

  				</div>

  				</p>
  			</div>
  			<div class="modal-footer">

          <%= f.submit "Edit", :id => "reinstall-modal-reinstall-btn", :class => "btn btn-danger"%>
  				<a href="#" class="btn" data-dismiss="modal">Cancel</a>
  			</div>
  		</div>
      <%end%>

    </div>
<script>
$(document).ready(function() {
	$('.edit').click(function() {
    fname = $(this).data('fname');
    lname = $(this).data('lname');
    uid = $(this).data('uid');
    email = $(this).data('email');
		modal = $('#modal');
    $('#user_fname').attr("value", fname);
    $('#user_lname').attr("value", lname);
    $('#user_userid').attr("value", uid);
    $('#user_email').attr("value", email);
		modal.modal('show');

	});
  });
  </script>
<%= render "shared/footer" %>

app/views/layouts/api.html.erb
<%= yield %>

app/views/shared/_admin_navbar_announcements.html.erb
<ul class="nav nav-tabs nav-fill w-100 lead mb-4" role="tablist">
  <li class="nav-item">
    <a href="<%= admin_path %>" class="nav-link fade-page">Home</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_announcements_path %>" class="nav-link active fade-page">Announcements</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_zones_path %>" class="nav-link fade-page">Zones</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_users_path %>" class="nav-link fade-page" >Users</a>
  </li>
</ul>

app/views/shared/_admin_navbar_home.html.erb
<ul class="nav nav-tabs nav-fill w-100 lead mb-4" role="tablist">
  <li class="nav-item">
    <a href="<%= admin_path %>" class="nav-link active fade-page">Home</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_announcements_path %>" class="nav-link fade-page">Announcements</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_zones_path %>" class="nav-link fade-page">Zones</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_users_path %>" class="nav-link fade-page" >Users</a>
  </li>
</ul>

app/views/shared/_admin_navbar_nodes.html.erb
<ul class="nav nav-tabs nav-fill w-100 lead mb-4" role="tablist">
  <li class="nav-item">
    <a href="<%= admin_path %>" class="nav-link fade-page">Home</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_announcements_path %>" class="nav-link fade-page">Announcements</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_zones_path %>" class="nav-link active fade-page">Zones</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_users_path %>" class="nav-link fade-page">Users</a>
  </li>
</ul>

app/views/shared/_admin_navbar_users.html.erb
<ul class="nav nav-tabs nav-fill w-100 lead mb-4" role="tablist">
  <li class="nav-item">
    <a href="<%= admin_path %>" class="nav-link fade-page">Home</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_announcements_path %>" class="nav-link fade-page">Announcements</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_zones_path %>" class="nav-link fade-page">Zones</a>
  </li>
  <li class="nav-item">
    <a href="<%= admin_users_path %>" class="nav-link active fade-page">Users</a>
  </li>
</ul>

app/views/shared/_alerts.html.erb
<% if ! Announcement.all.empty?
     Announcement.all.order(created_at: :asc).each do |a|  %>
  <div class="alert alert-dismissible d-none d-md-block bg-primary text-white py-4 py-md-3 px-0 mb-0 rounded-0 border-0">
  <div class="container">
    <div class="row no-gutters align-items-md-center justify-content-center">
      <div class="col-lg-11 col-md d-flex flex-column flex-md-row align-items-md-center justify-content-lg-center">
        <div class="mb-3 mb-md-0"><strong><%= raw a.announcements %></strong></div>
      </div>
    </div>
  </div>
</div>
<%end
  end %>

app/views/shared/_genericerror.html.erb
<div class="alert alert-danger alert-block">
						<button type="button" class="close" data-dismiss="alert">×</button>
						<h4>Oops!</h4>
  You've left something out!<br>
</div>