config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Signup
  root 'sessions#new'
  scope '/signup' do
    get '/'  => 'users#new', as: :signup
    post '/'  => 'users#create'
  end
  # Login
  scope '/login' do
    get '/'  => 'sessions#new', as: :login
    get '/error'  => 'sessions#error'
    get '/error/passwd'  => 'sessions#newpass'
    get '/session'  => 'sessions#loggedout'
    post '/'  => 'sessions#create'
  end
  # Logout
  scope '/logout' do
    get '/' => 'sessions#destroy', as: :logout
  end
  # Dashboard
  scope '/dash' do
    get '/' => 'dashboard#new', as: :dash
  end
  scope '/zone' do
    get '/:id' => 'zone#index', as: :zone
  end
  # Admin
  scope '/admin' do
    get '/' => 'admin#new', as: :admin
    # Users
    scope '/users' do
      get '/' => 'admin#users', as: :admin_users
      get '/lock/:id' => 'admin#lock_account', as: :admin_lock_user
      get '/unlock/:id' => 'admin#unlock_account', as: :admin_unlock_user
      scope '/make' do
        get '/admin/:id' => 'admin#make_admin', as: :admin_create_admin
        get '/user/:id' => 'admin#make_user', as: :admin_create_user
      end
      post '/edit' => 'admin#edit_user', as: :admin_edit_users
    end
    # Servers
    scope '/servers' do
        get '/' => 'admin#servers', as: :admin_servers
        get '/destroy/:id' => 'admin#destroy', as: :admin_destroy_servers
    end
    scope '/templates' do
      get '/' => 'admin#templates', as: :admin_templates
      post '/edit' => 'admin#edit_template', as: :admin_edit_templates
      get '/destroy/:id' => 'admin#destroy_template', as: :admin_destroy_templates
      post '/create' => 'admin#create_template', as: :admin_create_templates
    end
    scope '/groups' do
      get '/' => 'admin#groups', as: :admin_groups
      post '/edit' => 'admin#edit_group', as: :admin_edit_groups
      get '/destroy/:id' => 'admin#destroy_group', as: :admin_destroy_groups
      post '/create' => 'admin#create_group', as: :admin_create_groups
    end
    scope '/support' do
      get '/' => 'admin#support', as: :admin_support
      get '/closed' => 'admin#closed_tickets', as: :admin_support_closed
      get '/close/:id' => 'admin#close_ticket', as: :admin_support_close
      get '/open/:id' => 'admin#open_ticket', as: :admin_support_open
      get '/view/:id' => 'admin#view_ticket', as: :admin_support_view
      post '/reply/:id' => 'admin#reply_ticket', as: :admin_support_reply
    end
    scope '/announcements' do
      get '/' => 'admin#announcements', as: :admin_announcements
      post '/create' => 'admin#create_announcement', as: :admin_announcements_create
      get '/destroy/:id' => 'admin#destroy_announcement', as: :admin_announcements_destroy
      post '/edit' => 'admin#edit_announcement', as: :admin_announcements_edit
    end
    scope '/zones' do
      get '/' => 'admin#zones', as: :admin_zones
      get '/destroy/:id' => 'admin#destroy_node', as: :admin_zones_destroy
      post '/add' => 'admin#add_zone', as: :admin_create_zones
      get '/delete/:id' => 'admin#destroy_zone', as: :admin_destroy_zones
    end
    scope '/pools' do
      get '/' => 'admin#pools', as: :admin_pools
      post '/create' => 'admin#create_pool', as: :admin_pools_create
      get '/destroy/:id' => 'admin#destroy_pool', as: :admin_pools_destroy
    end
    scope '/plans' do
      get '/' => 'admin#plans', as: :admin_plans
      post '/create' => 'admin#create_plan', as: :admin_plans_create
      get '/destroy/:id' => 'admin#destroy_plan', as: :admin_plans_destroy
    end
  end
  # Account
  scope '/account' do
    get '/' => 'account#new', as: :account
    post '/' => 'account#update'
    get '/saved' => 'account#updated', as: :account_saved
    get '/error' => 'account#error', as: :account_error
  end
  # Activity
  scope '/activity' do
    get '/' => 'activity#new', as: :activity
  end
  # Reset
  scope '/reset' do
    get '/' => 'reset#new', as: :reset
    post '/' => 'reset#check'
    get '/error' => 'reset#chgerror', as: :reset_error_reset
    get '/done' => 'reset#done', as: :reset_done
    get '/:id' => 'reset#reset'
    post '/:id' => 'reset#change', as: :reset_reset
  end
  # Verify
  scope '/verify' do
    get '/' => 'verify#new', as: :verify
    post '/' => 'verify#verify'
    get '/error' => 'verify#error', as: :verify_error
  end
  scope '/api' do
    scope '/v1' do
      get '/auth' => 'api#authenticate'
      post '/register' => 'api#registeruser'
      post '/verify' => 'api#verify'
      get '/reset' => 'api#reset'
      get '/details' => 'api#userdetails'
      patch '/password' => 'api#userpasswd'
      get '/tickets' => 'api#supporttickets'
      get '/bills' => 'api#showbills'
      get '/logs' => 'api#showlogs'
      patch '/style' => 'api#updatestyle'
      scope '/bill' do
        get '/:id' => 'api#viewbill'
      end
      scope '/ticket' do
        get '/:id' => 'api#viewticket'
        post '/create' => 'api#createticket'
      end
      get '/run_accounting' => 'api#run_accounting'
      get '/run_generation' => 'api#run_generation'
    end
  end
  scope '/create' do
    get '/' => 'zone#create', as: :new_zone
    post '/' => 'zone#make'
  end
  scope '/errors' do
    get '/400' => 'errors#e400'
    get '/401' => 'errors#e401'
    get '/403' => 'errors#e403'
    get '/404' => 'errors#e404'
    get '/405' => 'errors#e405'
    get '/406' => 'errors#e406'
    get '/422' => 'errors#e422'
    get '/500' => 'errors#e500'
    get '/501' => 'errors#e501'
  end
end

app/models/action.rb
class Action < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/geo_ip.rb
class GeoIp < ApplicationRecord
end

app/models/geo_ip2_isp.rb
class GeoIp2Isp < ApplicationRecord
end

app/models/ip_pool.rb
class IpPool < ApplicationRecord
end

app/models/os_collection.rb
class OsCollection < ApplicationRecord
end

app/models/os_template.rb
class OsTemplate < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/restriction.rb
class Restriction < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/vm.rb
class Vm < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_secure_token :route_token, length: 32
end

app/controllers/verify_controller.rb
class VerifyController < ApplicationController
  before_action :require_user
  def new
  end
  def verify
    t = Time.now
    @ip = request.remote_ip
    @user = User.find_by(email: current_user.email)
    if params[:session][:code] == @user.activation_code
      @user.activated = '1'
      @user.activation_code = nil
      if @user.save
          @action = Action.create(:action => 'Verify Account', :owner => @user.email, :ip => @ip, :date => t.strftime("%Y-%m-%d"), :status => 'Success')
          @action.save
          redirect_to dash_path
        end
      else
        redirect_to verify_error_path
      end
  end
def error
end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verify_helper.rb
module VerifyHelper
end

app/helpers/zone_helper.rb
module ZoneHelper
end

app/views/verify/error.html.erb
<% content_for :title, "Verify your email" %>
<% content_for :new_layout, "1" %>

<style>body, html { overflow: hidden; }</style>

<div class="loader">
  <div class="loading-animation"></div>
</div>

<section class="row no-gutters p-0 bg-light min-vh-100">
  <div class="col-lg-6 d-none d-lg-block order-lg-2">
    <img class="flex-fill" src="/images/unsplash.jpg" alt="Image">
  </div>
  <div class="col-lg-6">
    <section class="p-0 bg-gradient text-white">
      <div class="container min-vh-lg-100 d-flex flex-column justify-content-between text-center py-4 py-md-5">
        <div class="row justify-content-center my-5">
          <div class="col-xl-7 col-lg-8">
            <h1 class="h2 text-center mb-lg-5"><%= image_tag "logo-text-white.png", :height => '55', :class => 'logo' %> </h1>
            <div class="card card-body shadow text-left text-dark custom-item-bg-dark">
              <div class="alert alert-primary" role="alert">
                Hm. That code didn't work. Please try again
              </div>
              <%= form_for(:session, url: verify_path, :html => {:class => 'vertical-form'}) do |f| %>
                <div class="form-group">
                  <%= f.text_field :code, :placeholder => "Verification Code", :maxlength => 12, :class => "form-control custom-input-dark"  %>
                </div>
                <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>

<a href="#top" class="btn btn-primary rounded-circle btn-back-to-top" data-smooth-scroll data-aos="fade-up" data-aos-offset="2000" data-aos-mirror="true" data-aos-once="false">
  <img src="/assets/img/icons/interface/icon-arrow-up.svg" alt="Icon" class="icon bg-white" data-inject-svg>
</a>

app/views/verify/new.html.erb
<% content_for :title, "Verify your email" %>
<% content_for :new_layout, "1" %>

<style>body, html { overflow: hidden; }</style>

<div class="loader">
  <div class="loading-animation"></div>
</div>

<section class="row no-gutters p-0 bg-light min-vh-100">
  <div class="col-lg-6 d-none d-lg-block order-lg-2">
    <img class="flex-fill" src="/images/unsplash.jpg" alt="Image">
  </div>
  <div class="col-lg-6">
    <section class="p-0 bg-gradient text-white">
      <div class="container min-vh-lg-100 d-flex flex-column justify-content-between text-center py-4 py-md-5">
        <div class="row justify-content-center my-5">
          <div class="col-xl-7 col-lg-8">
            <h1 class="h2 text-center mb-lg-5"><%= image_tag "logo-text-white.png", :height => '55', :class => 'logo' %> </h1>
            <div class="card card-body shadow text-left text-dark custom-item-bg-dark">
                <div class="alert alert-primary" role="alert">
                  We sent you a code! Please enter it here.
                </div>
              <%= form_for(:session, url: verify_path, :html => {:class => 'vertical-form'}) do |f| %>
                <div class="form-group">
                  <%= f.text_field :code, :placeholder => "Verification Code", :maxlength => 12, :class => "form-control custom-input-dark"  %>
                </div>
                <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>

<a href="#top" class="btn btn-primary rounded-circle btn-back-to-top" data-smooth-scroll data-aos="fade-up" data-aos-offset="2000" data-aos-mirror="true" data-aos-once="false">
  <img src="/assets/img/icons/interface/icon-arrow-up.svg" alt="Icon" class="icon bg-white" data-inject-svg>
</a>